#!/usr/bin/env python3
"""Derived versions of the manuscript: flat submission copy and arXiv preprint.

Reads paper/main_cmame.tex (the only hand-edited source) and writes

* paper/cmame_submission_flat/: main_cmame_submission.tex with the figures renamed
  Figure_<n>_<name>.png next to it, plus highlights and declarations; zipped as
  paper/cmame_submission_flat.zip;
* paper/arxiv/: main_arxiv.tex (article class, \\pdfoutput=1, inline bibliography), the figures,
  README.md with the submission metadata, arxiv_submission.zip and ARXIV_VERSION.json.

Both copies are generated deterministically; never edit them by hand.  Compile the arXiv copy with
`latexmk -pdf main_arxiv.tex` inside paper/arxiv/ to check it.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import sys
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAPER = HERE.parent
MAIN_TEX = PAPER / "main_cmame.tex"
FIGURES = PAPER / "figures"
FLAT = PAPER / "cmame_submission_flat"
FLAT_ZIP = PAPER / "cmame_submission_flat.zip"
ARXIV = PAPER / "arxiv"
ZIP_TIMESTAMP = (2026, 9, 21, 0, 0, 0)
ARXIV_ABSTRACT_LIMIT = 1920

AUTHOR_BLOCK = r"""\author{Jingquan Wang\\[3pt]
  \small Department of Mechanical Engineering, University of Wisconsin--Madison,\\
  \small 1513 University Avenue, Madison, WI 53706, United States\\
  \small \texttt{jingquanw@wisc.edu}}
\date{}"""

PREAMBLE_HEAD = r"""\pdfoutput=1
% arXiv preprint version, generated by paper/rewrite/build_derived.py from main_cmame.tex.
% Do not edit by hand: edit main_cmame.tex and rerun the generator.
\documentclass[11pt,a4paper]{article}

\usepackage[margin=1in]{geometry}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amsmath,amssymb,amsfonts,amsthm}
\usepackage{array}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{url}
\usepackage{xcolor}
\usepackage[colorlinks=true,linkcolor=blue,citecolor=blue,urlcolor=blue]{hyperref}
\providecommand{\nolinkurl}[1]{\url{#1}}
\emergencystretch=4em
"""

SUGGESTED_CATEGORIES = [
    "math.NA (Numerical Analysis) - primary",
    "cs.CE (Computational Engineering, Finance, and Science) - cross-list",
    "physics.comp-ph (Computational Physics) - optional cross-list",
]


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def extract_between(text: str, start: str, end: str) -> str:
    i = text.index(start) + len(start)
    j = text.index(end, i)
    return text[i:j]


def figure_order(main: str) -> list[str]:
    names = re.findall(r"\\paperfig\{\\figpath/([A-Za-z0-9_]+\.png)\}", main)
    seen: list[str] = []
    for n in names:
        if n not in seen:
            seen.append(n)
    return seen


def flat_mapping(main: str) -> dict[str, str]:
    return {name: f"Figure_{k + 1}_{name}" for k, name in enumerate(figure_order(main))}


def write_zip(path: Path, root: Path, names: list[str]) -> None:
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for name in names:
            info = zipfile.ZipInfo(name, date_time=ZIP_TIMESTAMP)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, (root / name).read_bytes())


def build_flat(main: str) -> dict:
    mapping = flat_mapping(main)
    if FLAT.exists():
        for old in FLAT.iterdir():
            if old.is_file():
                old.unlink()
    FLAT.mkdir(exist_ok=True)
    tex = main.replace("\\newcommand{\\figpath}{figures}", "\\newcommand{\\figpath}{.}")
    for name, flat_name in mapping.items():
        tex = tex.replace("\\figpath/" + name, "\\figpath/" + flat_name)
        shutil.copyfile(FIGURES / name, FLAT / flat_name)
    (FLAT / "main_cmame_submission.tex").write_text(tex, encoding="utf-8")
    for extra in ("highlights_cmame.txt", "declarations_cmame.md"):
        if (PAPER / extra).exists():
            shutil.copyfile(PAPER / extra, FLAT / extra)
    names = ["main_cmame_submission.tex"] + sorted(mapping.values()) + [e for e in ("highlights_cmame.txt", "declarations_cmame.md") if (FLAT / e).exists()]
    write_zip(FLAT_ZIP, FLAT, names)
    return {"figures": sorted(mapping.values()), "tex_sha256": sha256_text(tex)}


def plain_abstract(abstract: str) -> str:
    text = abstract.replace("\\method{}", "Gauss6/FullVA").replace("\\tfe{}", "TFE").replace("~", " ")
    text = re.sub(r"\\\((.*?)\\\)", lambda m: m.group(1), text, flags=re.S)
    text = text.replace("$", "").replace("Lean~4", "Lean 4").replace("--", "-")
    text = re.sub(r"\\[A-Za-z]+", "", text)
    return " ".join(text.split())


def build_arxiv(main: str) -> dict:
    title = re.search(r"^\\title\{(.*)\}\s*$", main, flags=re.M).group(1)
    abstract = extract_between(main, "\\begin{abstract}", "\\end{abstract}").strip("\n")
    keywords = " ".join(extract_between(main, "\\begin{keyword}", "\\end{keyword}").strip().replace("\\sep", ";").split())
    macros = "\\newtheorem{assumption}{Assumption}" + extract_between(main, "\\newtheorem{assumption}{Assumption}", "\\begin{document}").rstrip() + "\n"
    macros = macros.replace("\\newcommand{\\figpath}{figures}", "\\newcommand{\\figpath}{.}")
    body = main[main.index("\\section{Introduction}"):]
    mapping = flat_mapping(main)
    for name, flat_name in mapping.items():
        body = body.replace("\\figpath/" + name, "\\figpath/" + flat_name)
    tex = (PREAMBLE_HEAD + "\n" + macros + "\n\\begin{document}\n\n" + "\\title{" + title + "}\n" + AUTHOR_BLOCK + "\n\n\\maketitle\n\n"
           + "\\begin{abstract}\n" + abstract + "\n\\end{abstract}\n\n" + "\\medskip\\noindent\\textbf{Keywords:} " + keywords + "\n\n" + body)
    plain = plain_abstract(abstract)
    if len(plain) > ARXIV_ABSTRACT_LIMIT:
        raise RuntimeError(f"plain abstract has {len(plain)} characters, above the arXiv limit of {ARXIV_ABSTRACT_LIMIT}")
    ARXIV.mkdir(exist_ok=True)
    for old in ARXIV.glob("Figure_*.png"):
        old.unlink()
    for name, flat_name in mapping.items():
        shutil.copyfile(FIGURES / name, ARXIV / flat_name)
    (ARXIV / "main_arxiv.tex").write_text(tex, encoding="utf-8")
    figures = sorted(mapping.values())
    readme = (f"# arXiv version\n\nGenerated from `../main_cmame.tex` by `../rewrite/build_derived.py`; do not edit `main_arxiv.tex` by hand.\n"
              f"Compile with `latexmk -pdf main_arxiv.tex` (pdflatex; the bibliography is inline, no BibTeX run).\n\n"
              f"## Metadata\n\n**Title.** {title}\n\n**Abstract** ({len(plain)} characters, limit {ARXIV_ABSTRACT_LIMIT}):\n\n{plain}\n\n"
              f"**Suggested categories.**\n" + "\n".join(f"- {c}" for c in SUGGESTED_CATEGORIES)
              + f"\n\n**Comments field (suggestion).** {len(figures)} figures. Lean 4/Mathlib development and experiment scripts accompany the manuscript.\n\n"
              f"## Upload\n\nUpload `arxiv_submission.zip`; arXiv detects the main file automatically.\n\n## Figures\n\n" + "\n".join(f"- `{f}`" for f in figures) + "\n")
    (ARXIV / "README.md").write_text(readme, encoding="utf-8")
    (ARXIV / ".gitignore").write_text("*.aux\n*.out\n*.fls\n*.fdb_latexmk\n*.synctex.gz\n*.toc\n", encoding="utf-8")
    write_zip(ARXIV / "arxiv_submission.zip", ARXIV, ["main_arxiv.tex"] + figures)
    manifest = {"schema": "arxiv-version-v2", "source": "main_cmame.tex", "source_sha256": sha256_text(main), "output_tex": "arxiv/main_arxiv.tex",
                "output_tex_sha256": sha256_text(tex), "document_class": "article", "figures": figures, "figure_count": len(figures),
                "plain_abstract_characters": len(plain), "plain_abstract_within_limit": True, "bibliography": "inline_thebibliography_no_bbl_needed",
                "suggested_categories": SUGGESTED_CATEGORIES, "zip_sha256": hashlib.sha256((ARXIV / "arxiv_submission.zip").read_bytes()).hexdigest()}
    (ARXIV / "ARXIV_VERSION.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def main() -> int:
    main_tex = MAIN_TEX.read_text(encoding="utf-8")
    flat = build_flat(main_tex)
    arx = build_arxiv(main_tex)
    print(f"flat: {len(flat['figures'])} figures -> {FLAT.name}/, {FLAT_ZIP.name}")
    print(f"arxiv: {arx['figure_count']} figures, abstract {arx['plain_abstract_characters']} chars -> {ARXIV.name}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
