#!/usr/bin/env python3
"""Derive the arXiv preprint version of the CMAME manuscript.

`arxiv/main_arxiv.tex` is generated from `main_cmame.tex` by a deterministic transformation:

* the `elsarticle` preamble and `frontmatter` are replaced by a plain `article`-class preprint
  template (geometry, amsmath/amsthm, booktabs, graphicx, hyperref with coloured links);
* the manuscript's own theorem environments and macros (`\\method`, `\\tfe`, `\\paperfig`, column
  type `P`) are copied verbatim from the CMAME preamble, so the two sources cannot drift;
* the body from `\\section{Introduction}` to `\\end{document}` is copied verbatim except that the
  figure paths `\\figpath/<name>.png` become the flat `Figure_<n>_<name>.png` files used by the
  Elsevier flat copy, which are copied next to the source;
* the inline `thebibliography` is kept, so no `.bbl` is needed on arXiv;
* `\\pdfoutput=1` is the first line so that arXiv's build uses pdflatex for the PNG figures.

Also written: `arxiv/README.md` (arXiv metadata: title, plain-text abstract within the 1920
character limit, suggested categories, upload steps) and `arxiv/arxiv_submission.zip` (source
plus figures, fixed timestamps).  Compile with `latexmk -pdf main_arxiv.tex` inside `arxiv/`.
The generator changes no claim state; `validate_arxiv_version.py` checks that the derived file
is in sync with the CMAME source.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import sys
import zipfile
from pathlib import Path

PAPER = Path(__file__).resolve().parent
from paper_paths import LATEX, package_path as manuscript_path
MAIN_TEX = LATEX / "main_cmame.tex"
FLAT_TEX = LATEX / "cmame_submission_flat" / "main_cmame_submission.tex"
FLAT_DIR = LATEX / "cmame_submission_flat"
ARXIV = LATEX / "arxiv"
OUT_TEX = ARXIV / "main_arxiv.tex"
OUT_README = ARXIV / "README.md"
OUT_ZIP = ARXIV / "arxiv_submission.zip"
OUT_MANIFEST = ARXIV / "ARXIV_VERSION.json"

ARXIV_ABSTRACT_LIMIT = 1920
ZIP_TIMESTAMP = (2026, 9, 20, 0, 0, 0)

AUTHOR_BLOCK = r"""\author{Jingquan Wang\\[3pt]
  \small Department of Mechanical Engineering, University of Wisconsin--Madison,\\
  \small 1513 University Avenue, Madison, WI 53706, United States\\
  \small \texttt{jingquanw@wisc.edu}}
\date{}"""

PREAMBLE_HEAD = r"""\pdfoutput=1
% arXiv preprint version, generated by build_arxiv_version.py from main_cmame.tex.
% Do not edit by hand: edit main_cmame.tex and rerun the generator.
\documentclass[11pt,a4paper]{article}

\usepackage[margin=1in]{geometry}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amsmath,amssymb,amsfonts,amsthm}
\usepackage{array}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{url}
\usepackage{xcolor}
\usepackage[colorlinks=true,linkcolor=blue,citecolor=blue,urlcolor=blue]{hyperref}
\providecommand{\nolinkurl}[1]{\url{#1}}
\emergencystretch=4em
"""

SUGGESTED_CATEGORIES = [
    "math.NA (Numerical Analysis) - primary",
    "cs.CE (Computational Engineering, Finance, and Science) - cross-list",
    "physics.comp-ph (Computational Physics) - optional cross-list",
]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def figure_map() -> dict[str, str]:
    """`<name>.png` -> `Figure_<n>_<name>.png`, harvested from the Elsevier flat copy."""
    flat = read_text(FLAT_TEX)
    pairs = re.findall(r"\\paperfig\{(Figure_\d+_([A-Za-z0-9_]+\.png))\}", flat)
    mapping = {name: full for full, name in pairs}
    if not mapping:
        raise RuntimeError("no flat figure names found in the Elsevier flat copy")
    return mapping


def extract_between(text: str, start: str, end: str) -> str:
    i = text.index(start) + len(start)
    j = text.index(end, i)
    return text[i:j]


def manuscript_parts(main: str) -> dict[str, str]:
    title = re.search(r"^\\title\{(.*)\}\s*$", main, flags=re.M).group(1)
    abstract = extract_between(main, "\\begin{abstract}", "\\end{abstract}").strip("\n")
    keywords = extract_between(main, "\\begin{keyword}", "\\end{keyword}").strip()
    keywords = " ".join(keywords.replace("\\sep", ";").split())
    macros = extract_between(main, "\\newtheorem{assumption}{Assumption}", "\\begin{document}")
    macros = "\\newtheorem{assumption}{Assumption}" + macros.rstrip() + "\n"
    if "\\newcommand{\\figpath}{figures}" not in macros:
        raise RuntimeError("figpath macro not found in the CMAME preamble")
    macros = macros.replace("\\newcommand{\\figpath}{figures}", "\\newcommand{\\figpath}{.}")
    body_start = main.index("\\section{Introduction}")
    body = main[body_start:]
    if "\\end{document}" not in body:
        raise RuntimeError("end of document not found")
    return {"title": title, "abstract": abstract, "keywords": keywords, "macros": macros, "body": body}


def substitute_figures(body: str, mapping: dict[str, str]) -> tuple[str, list[str]]:
    used: list[str] = []

    def sub(match: re.Match[str]) -> str:
        name = match.group(1)
        if name not in mapping:
            raise RuntimeError(f"figure {name} has no flat counterpart")
        used.append(mapping[name])
        return "\\paperfig{" + mapping[name] + "}"

    out = re.sub(r"\\paperfig\{\\figpath/([A-Za-z0-9_]+\.png)\}", sub, body)
    if "\\figpath/" in out:
        raise RuntimeError("unmapped figpath reference remains in the body")
    return out, used


def plain_abstract(abstract: str) -> str:
    """Plain-text abstract for the arXiv metadata field."""
    text = abstract.replace("\\method{}", "Gauss6/FullVA").replace("\\tfe{}", "TFE").replace("~", " ")
    text = re.sub(r"\\\((.*?)\\\)", lambda m: m.group(1), text, flags=re.S)
    text = text.replace("$", "")
    text = text.replace("\\eta_h\\le c_\\eta h^7", "eta_h <= c_eta h^7")
    text = text.replace("Lean~4", "Lean 4").replace("--", "-")
    text = re.sub(r"\\[A-Za-z]+", "", text)
    return " ".join(text.split())


def render_tex(parts: dict[str, str], body: str) -> str:
    return (
        PREAMBLE_HEAD
        + "\n"
        + parts["macros"]
        + "\n\\begin{document}\n\n"
        + "\\title{" + parts["title"] + "}\n"
        + AUTHOR_BLOCK + "\n\n"
        + "\\maketitle\n\n"
        + "\\begin{abstract}\n" + parts["abstract"] + "\n\\end{abstract}\n\n"
        + "\\medskip\\noindent\\textbf{Keywords:} " + parts["keywords"] + "\n\n"
        + body
    )


def render_readme(parts: dict[str, str], figures: list[str], abstract_plain: str) -> str:
    cats = "\n".join(f"- {c}" for c in SUGGESTED_CATEGORIES)
    figs = "\n".join(f"- `{f}`" for f in figures)
    return f"""# arXiv version

Generated from `../main_cmame.tex` by `../../validation/paper_v047_cylindrical_chain/build_arxiv_version.py`; do not edit `main_arxiv.tex`
by hand.  Compile locally with `latexmk -pdf main_arxiv.tex` (pdflatex, TeX Live 2023 or later;
no BibTeX run is needed because the bibliography is inline).

## Metadata for the arXiv submission form

**Title.** {parts['title']}

**Abstract** ({len(abstract_plain)} characters, limit {ARXIV_ABSTRACT_LIMIT}):

{abstract_plain}

**Suggested categories.**
{cats}

**Comments field (suggestion).** {len(figures)} figures. Lean 4/Mathlib development and
reproducibility records accompany the manuscript.

## Upload

1. Upload `arxiv_submission.zip` (this directory's `main_arxiv.tex` and the figures listed below;
   arXiv detects the main file automatically).
2. Choose the license (arXiv non-exclusive license is the minimal choice; CC BY 4.0 if the journal
   policy allows it).
3. Paste the title, abstract and categories above.

## Figures shipped in the archive

{figs}
"""


def write_zip(tex_name: str, figures: list[str]) -> None:
    with zipfile.ZipFile(OUT_ZIP, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for name in [tex_name] + sorted(figures):
            info = zipfile.ZipInfo(name, date_time=ZIP_TIMESTAMP)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, (ARXIV / name).read_bytes())


def build(write: bool = True) -> dict:
    main = read_text(MAIN_TEX)
    parts = manuscript_parts(main)
    mapping = figure_map()
    body, used = substitute_figures(parts["body"], mapping)
    figures = sorted(set(used))
    tex = render_tex(parts, body)
    abstract_plain = plain_abstract(parts["abstract"])
    if len(abstract_plain) > ARXIV_ABSTRACT_LIMIT:
        raise RuntimeError(f"plain abstract has {len(abstract_plain)} characters, above the arXiv limit")
    readme = render_readme(parts, figures, abstract_plain)
    manifest = {
        "schema": "arxiv-version-v1",
        "source": "main_cmame.tex",
        "source_sha256": sha256_text(main),
        "output_tex": "arxiv/main_arxiv.tex",
        "output_tex_sha256": sha256_text(tex),
        "document_class": "article",
        "figures": figures,
        "figure_count": len(figures),
        "plain_abstract_characters": len(abstract_plain),
        "plain_abstract_within_limit": len(abstract_plain) <= ARXIV_ABSTRACT_LIMIT,
        "bibliography": "inline_thebibliography_no_bbl_needed",
        "suggested_categories": SUGGESTED_CATEGORIES,
        "claim_state_change": False,
        "run_v047_invoked": False,
    }
    if write:
        ARXIV.mkdir(exist_ok=True)
        OUT_TEX.write_text(tex, encoding="utf-8")
        for name in figures:
            shutil.copyfile(FLAT_DIR / name, ARXIV / name)
        OUT_README.write_text(readme, encoding="utf-8")
        (ARXIV / ".gitignore").write_text("*.aux\n*.out\n*.fls\n*.fdb_latexmk\n*.synctex.gz\n*.toc\n", encoding="utf-8")
        write_zip(OUT_TEX.name, figures)
        manifest["zip_sha256"] = hashlib.sha256(OUT_ZIP.read_bytes()).hexdigest()
        OUT_MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return {"tex": tex, "readme": readme, "manifest": manifest, "figures": figures}


def main() -> int:
    result = build(write=True)
    m = result["manifest"]
    print("arxiv_version=written")
    print(f"tex_lines={result['tex'].count(chr(10))}")
    print(f"figures={m['figure_count']}")
    print(f"plain_abstract_characters={m['plain_abstract_characters']}")
    print(f"zip={OUT_ZIP.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
